# Generated by Django 4.2 on 2023-06-02 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_department', models.AutoField(primary_key=True, serialize=False, verbose_name='id департамента')),
                ('name_department', models.CharField(max_length=256, verbose_name='Наименование департамента')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employee', models.AutoField(primary_key=True, serialize=False, verbose_name='id сотрудника')),
                ('name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('photo', models.ImageField(blank=True, max_length=256, null=True, upload_to='foto/', verbose_name='Фотография')),
                ('post', models.CharField(max_length=256, verbose_name='Должность')),
                ('salary', models.FloatField(max_length=10, verbose_name='Оклад')),
                ('age', models.PositiveSmallIntegerField(max_length=3, verbose_name='Возраст')),
                ('id_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Employee_Department', to='main.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'Employee',
            },
        ),
    ]
